name: 'Get Commit SHA'
description: 'get the commit SHA of the current commit'

inputs:
  short:
    description: 'shorten the commit SHA'
    required: false
    default: 'false'

outputs:
  COMMIT_SHA:
    description: 'the commit SHA'
    value: ${{ steps.get-commit-sha.outputs.COMMIT_SHA }}

runs:
  using: 'composite'
  steps:
    - name: '⛓️ Get Commit SHA'
      id: get-commit-sha
      shell: bash
      run: |
        if [[ "${{ inputs.short }}" == 'true' ]]; then
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        else
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
        fi
